version: "3"
services:
  ui:
    build:
      context: ./ui-web-app-reactjs
      dockerfile: Dockerfile
    image: kunchalavikram/ms-ui:1.0
    depends_on:
      - zuul
    ports:
      - "80:8080"
    networks:
      - my_net

  zuul:
    build:
      context: ./zuul-api-gateway
      dockerfile: Dockerfile
    image: kunchalavikram/ms-zuul:1.0
    depends_on:
      - shoes
      - cart
      - offers
      - wishlist
    ports:
      - "9999:9999"
    networks:
      - my_net

  shoes:
    build:
      context: ./shoes-microservice-spring-boot
      dockerfile: Dockerfile
    image: kunchalavikram/ms-shoes:1.0
    ports:
      - "1002:1002"
    networks:
      - my_net
  
  cart:
    build:
      context: ./cart-microservice-nodejs
      dockerfile: Dockerfile
    image: kunchalavikram/ms-cart:1.0
    ports:
      - "1004:1004"
    networks:
      - my_net

  offers:
    build:
      context: ./offers-microservice-spring-boot
      dockerfile: Dockerfile
    image: kunchalavikram/ms-offers:1.0
    ports:
      - "1001:1001"
    networks:
      - my_net

  wishlist:
    build:
      context: ./wishlist-microservice-python
      dockerfile: Dockerfile
    image: kunchalavikram/ms-wishlist:1.0
    ports:
      - "5000:5000"
    networks:
      - my_net

networks:
  my_net:
